### ISSUE TITLE
Important: Div wrappers

### ISSUE THREAD

**Issue by blerude** [y-murayama/prj-rev-bwfs-dasmoto#1]
https://github.com/y-murayama/prj-rev-bwfs-dasmoto/blob/master/Dasmoto'sArts%26Crafts/index.html#L10-L13

You should wrap groups of related elements like this one in a div so that it's easy to see that they are related and so that you can easily apply stylings to the entire group vs. needing to do so on an individual basis.

**Comment by y-murayama** [comment]
Thanks, 
If it's wrapped in "div", what is the best way to style h2 ?
What do you think of my code below ? 

  ＜div id="brushes"＞
    ＜h2＞Brushes</h2＞
    ＜img src="resources/images/hacksaw.jpeg" /＞
    ＜h3＞Hacksaw Brushes</h3＞
    ＜p＞~~.＜/p＞
  ＜/div＞

-----------CSS-----------------
h2{
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

＃brushes h2{
  background-color: mediumspringgreen;
}

**Comment by blerude** [comment]
This looks great! Perfect styling and application of the id and the h2.

**Comment by y-murayama** [comment]
Good to hear that !
Thank you so much.
