### ISSUE TITLE
Simplify: One class

### ISSUE THREAD

**Issue by blerude** [y-murayama/prj-rev-bwfs-dasmoto#4]
https://github.com/y-murayama/prj-rev-bwfs-dasmoto/blob/master/Dasmoto'sArts%26Crafts/resources/style.css#L32-L38

Instead of having two classes here, why not just make one class--maybe called 'price'--that contains these two stylings. You can do this because they are both used together every time, never one without the other.

**Comment by y-murayama** [comment]
Thank you for the review.
I have a question about this.
If I wanted to add more style like another bold text with red, not only blue, should I make each class, "blue  bold" and "red bold" ?  If the code was more complicated, I might use "bold" itself and also bold and colors or other stylings, in that case, would it be better to make classes with some stylings ? or make each class with single styling then apply a few classes to HTML file like I did ?

**Comment by blerude** [comment]
If you apply all the same colors/bold to every element every time, you might as well make one class. But if you use 'red' for some elements and 'blue' for others and mix and match, then having individual classes makes sense. In this case, blue and bold went hand in hand every time, so I suggested merging the classes. Does that answer your question?

**Comment by y-murayama** [comment]
I understand.
Thank you so much !
